HEADER_1_FONT = 'Roboto 14 bold'
BODY_1_FONT = 'Roboto 12'
BUTTON_FONT = 'Roboto 14'
TABLE_MSG_FONT = 'Roboto 14 italic'

FIELD_FRAME_PAD = 20
FIELD_ENTRY_PAD = 5
FIELD_LABEL_PAD = 15
DELETE_BUTTON_PAD_X = (30, 15)
BUTTON_BELOW_PAD_Y = (0, 20)
DATE_PICKER_WIDTH = 12
LT_BORDER_WIDTH = 3
TIME_RANGE_OFFSET = 40
DTWINDOW_BOTTOM_PAD = 20
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 1000