FIELD_FRAME_PAD = 20
FIELD_ENTRY_PAD = 5
HEADER_1_FONT = 'Roboto 14 bold'
BODY_1_FONT = 'Roboto 12'
BUTTON_FONT = 'Roboto 14'
TABLE_MSG_FONT = 'Roboto 14 italic'

FIELD_FRAME_PAD = 20
FIELD_LABEL_PAD = 15
FIELD_ENTRY_PAD = 5
DELETE_BUTTON_PAD_X = (30, 15)
BUTTON_BELOW_PAD = (0, 20)
FIELD_ENTRY_LEFT_PAD = (15, FIELD_ENTRY_PAD)
FIELD_LEFT_PAD = (30, FIELD_ENTRY_PAD)
LEFT_INDENT_1_PAD = (40, FIELD_FRAME_PAD)
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 1000